name: flutter_ukn_earning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.24.0
  flutter_local_notifications: ^17.1.2
  googleapis_auth: ^1.6.0
  google_mobile_ads: ^5.1.0
  intl: ^0.19.0
  calendar_date_picker2: ^1.1.5
  image_picker: ^1.1.2
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.6
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.20
  lottie: ^3.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/common/
    - assets/images/auth/
    - assets/images/reward_history/
    - assets/images/intro/
    - assets/images/chat/
    - assets/images/home/
    - assets/json/
    - assets/images/admin/
    - assets/images/profile/

  fonts: 
    - family: Inter
      fonts:
        - asset: assets/font/inter_regular.ttf
          weight: 500
        - asset: assets/font/inter_medium.ttf
          weight: 600
        - asset: assets/font/inter_bold.ttf
          weight: 700
        - asset: assets/font/inter_semibold.ttf
          weight: 800
        - asset: assets/font/inter_extra_bold.ttf
          weight: 900